// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/gogo/protobuf/protoc-gen-gogo"
	_ "github.com/golang/protobuf/protoc-gen-go"
	_ "github.com/uber/prototool/cmd/prototool"
)
